//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingTool.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_members
    {
        public Nullable<int> team_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public int id { get; set; }
    
        public virtual members members { get; set; }
        public virtual teams teams { get; set; }
    }
}
