//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingTool.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class teams
    {
        public teams()
        {
            this.team_members = new HashSet<team_members>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> isactive { get; set; }
    
        public virtual ICollection<team_members> team_members { get; set; }
    }
}
